### PR TITLE
Dannon/Array/Day2

### PR DESCRIPTION
**Pull request by Dannon10**
Dannon Abayomi

### CODE REVIEW

**Review by Olixpin — CHANGES_REQUESTED** [review]
Please add your snapshot(screenshot) of your Leetcode acceptance solution.

**Review by Dannon10 — COMMENTED** [review]
added snapshot

**Review by Dannon10 — COMMENTED** [review]
added snapshot

**Review by Dannon10 — COMMENTED** [review]
added snapshot

**Review by Dannon10 — COMMENTED** [review]
Dannon

**Pull request merged**
